# Azure DevOps Pipeline for Team Image Builds
# Repository: microsoft.devcenter-images (Developer Repository)
# This pipeline builds team-specific DevBox images

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - packer/teams/**
      - definitions/devbox-definitions.json

pr: none

pool:
  vmImage: 'windows-latest'

variables:
  - group: devbox-images-credentials  # SP with gallery access only
  - group: devbox-infrastructure-config  # Gallery/DevCenter names
  - name: imageVersion
    value: '$(Build.BuildNumber)'

stages:
  - stage: ValidateInfrastructureAccess
    displayName: 'Validate Infrastructure Access'
    jobs:
      - job: CheckGalleryAccess
        displayName: 'Verify Gallery Access'
        steps:
          - checkout: self
          
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'DevBox-Images-ServiceConnection'
              scriptType: 'pscore'
              scriptLocation: 'inlineScript'
              inlineScript: |
                Write-Host "=========================================="
                Write-Host "Validating Infrastructure Configuration"
                Write-Host "=========================================="
                Write-Host ""
                
                # Read infrastructure config
                $config = Get-Content "config/infrastructure-config.json" | ConvertFrom-Json
                $env = $config.environments.prod
                
                Write-Host "Target Environment: Production" -ForegroundColor Cyan
                Write-Host "  Gallery Name: $($env.galleryName)" -ForegroundColor Gray
                Write-Host "  Gallery RG: $($env.galleryResourceGroup)" -ForegroundColor Gray
                Write-Host "  DevCenter: $($env.devCenterName)" -ForegroundColor Gray
                Write-Host "  Region: $($env.region)" -ForegroundColor Gray
                Write-Host ""
                
                # Verify gallery exists and we have access
                Write-Host "Verifying gallery access..." -ForegroundColor Cyan
                $gallery = az sig show `
                  --resource-group $env.galleryResourceGroup `
                  --gallery-name $env.galleryName `
                  --query "{name: name, location: location}" 2>&1
                
                if ($LASTEXITCODE -ne 0) {
                  Write-Error "Cannot access gallery. Check service principal permissions."
                  Write-Host "Gallery: $($env.galleryName)" -ForegroundColor Red
                  Write-Host "Resource Group: $($env.galleryResourceGroup)" -ForegroundColor Red
                  exit 1
                }
                
                $galleryInfo = $gallery | ConvertFrom-Json
                Write-Host "✓ Gallery access confirmed" -ForegroundColor Green
                Write-Host "  Location: $($galleryInfo.location)" -ForegroundColor Gray
                Write-Host ""
                
                # Check for baseline image
                Write-Host "Checking for baseline image..." -ForegroundColor Cyan
                $baseline = az sig image-definition show `
                  --resource-group $env.galleryResourceGroup `
                  --gallery-name $env.galleryName `
                  --gallery-image-definition $env.baselineImageName `
                  --query "name" -o tsv 2>&1
                
                if ($LASTEXITCODE -ne 0) {
                  Write-Error "Baseline image not found: $($env.baselineImageName)"
                  Write-Host "Infrastructure team must build baseline first." -ForegroundColor Yellow
                  exit 1
                }
                
                Write-Host "✓ Baseline image found: $baseline" -ForegroundColor Green
                Write-Host ""
                Write-Host "Ready to build team images" -ForegroundColor Green
            displayName: 'Validate Infrastructure Access'

  - stage: BuildTeamImages
    displayName: 'Build Team-Specific Images'
    dependsOn: ValidateInfrastructureAccess
    condition: succeeded()
    jobs:
      - job: DetermineChangedImages
        displayName: 'Detect Changed Images'
        steps:
          - checkout: self
            fetchDepth: 2
          
          - pwsh: |
              Write-Host "=== Detecting which images need to be rebuilt ===" -ForegroundColor Cyan
              Write-Host ""
              
              # Get changed files in last commit
              Write-Host "DEBUG: Running git diff HEAD~1 HEAD" -ForegroundColor Yellow
              $changedFiles = git diff --name-only HEAD~1 HEAD
              
              Write-Host "DEBUG: Changed files count: $($changedFiles.Count)" -ForegroundColor Yellow
              if ($changedFiles) {
                Write-Host "DEBUG: Changed files:" -ForegroundColor Yellow
                foreach ($f in $changedFiles) {
                  Write-Host "  - $f" -ForegroundColor Gray
                }
              } else {
                Write-Host "DEBUG: No changed files detected" -ForegroundColor Yellow
              }
              Write-Host ""
              
              $buildVSCode = $false
              $buildJava = $false
              $buildDotNet = $false
              $buildDataScience = $false
              
              foreach ($file in $changedFiles) {
                Write-Host "DEBUG: Checking file: $file" -ForegroundColor Gray
                if ($file -match "images/packer/teams/vscode") { 
                  Write-Host "  -> Matched vscode pattern!" -ForegroundColor Green
                  $buildVSCode = $true 
                }
                if ($file -match "images/packer/teams/java") { 
                  Write-Host "  -> Matched java pattern!" -ForegroundColor Green
                  $buildJava = $true 
                }
                if ($file -match "images/packer/teams/dotnet") { 
                  Write-Host "  -> Matched dotnet pattern!" -ForegroundColor Green
                  $buildDotNet = $true 
                }
                if ($file -match "images/packer/teams/datascience") { 
                  Write-Host "  -> Matched datascience pattern!" -ForegroundColor Green
                  $buildDataScience = $true 
                }
                if ($file -match "images/definitions/devbox-definitions.json") {
                  Write-Host "  -> Matched definitions! Rebuilding all images" -ForegroundColor Green
                  # If definitions changed, rebuild all
                  $buildVSCode = $true
                  $buildJava = $true
                  $buildDotNet = $true
                  $buildDataScience = $true
                }
              }
              
              Write-Host ""
              Write-Host "=== Build Decisions ===" -ForegroundColor Cyan
              Write-Host "  VSCode: $buildVSCode" -ForegroundColor $(if($buildVSCode){'Green'}else{'Gray'})
              Write-Host "  Java: $buildJava" -ForegroundColor $(if($buildJava){'Green'}else{'Gray'})
              Write-Host "  .NET: $buildDotNet" -ForegroundColor $(if($buildDotNet){'Green'}else{'Gray'})
              Write-Host "  DataScience: $buildDataScience" -ForegroundColor $(if($buildDataScience){'Green'}else{'Gray'})
              Write-Host ""
              
              # Set output variables
              Write-Host "DEBUG: Setting output variables" -ForegroundColor Yellow
              Write-Host "##vso[task.setvariable variable=buildVSCode;isOutput=true]$buildVSCode"
              Write-Host "DEBUG: Set buildVSCode = $buildVSCode" -ForegroundColor Yellow
              Write-Host "##vso[task.setvariable variable=buildJava;isOutput=true]$buildJava"
              Write-Host "DEBUG: Set buildJava = $buildJava" -ForegroundColor Yellow
              Write-Host "##vso[task.setvariable variable=buildDotNet;isOutput=true]$buildDotNet"
              Write-Host "DEBUG: Set buildDotNet = $buildDotNet" -ForegroundColor Yellow
              Write-Host "##vso[task.setvariable variable=buildDataScience;isOutput=true]$buildDataScience"
              Write-Host "DEBUG: Set buildDataScience = $buildDataScience" -ForegroundColor Yellow
            name: detectChanges
            displayName: 'Detect Changed Images'
      
      - job: BuildImages
        displayName: 'Build Team Images'
        dependsOn: DetermineChangedImages
        strategy:
          matrix:
            VSCode:
              imageType: 'vscode'
              imageFile: 'vscode-devbox.pkr.hcl'
              shouldBuild: $[ dependencies.DetermineChangedImages.outputs['detectChanges.buildVSCode'] ]
            Java:
              imageType: 'java'
              imageFile: 'java-devbox.pkr.hcl'
              shouldBuild: $[ dependencies.DetermineChangedImages.outputs['detectChanges.buildJava'] ]
            DotNet:
              imageType: 'dotnet'
              imageFile: 'dotnet-devbox.pkr.hcl'
              shouldBuild: $[ dependencies.DetermineChangedImages.outputs['detectChanges.buildDotNet'] ]
            DataScience:
              imageType: 'datascience'
              imageFile: 'datascience-devbox.pkr.hcl'
              shouldBuild: $[ dependencies.DetermineChangedImages.outputs['detectChanges.buildDataScience'] ]
        timeoutInMinutes: 120
        steps:
          - checkout: self
            condition: eq(variables['shouldBuild'], 'True')
          
          - task: PackerInstaller@1
            condition: eq(variables['shouldBuild'], 'True')
            inputs:
              version: 'latest'
            displayName: 'Install Packer'
          
          - task: AzureCLI@2
            condition: eq(variables['shouldBuild'], 'True')
            inputs:
              azureSubscription: 'DevBox-Images-ServiceConnection'
              scriptType: 'pscore'
              scriptLocation: 'inlineScript'
              inlineScript: |
                Write-Host "=========================================="
                Write-Host "Building $(imageType) DevBox Image"
                Write-Host "=========================================="
                Write-Host ""
                
                # Read infrastructure config
                $config = Get-Content "$(Build.SourcesDirectory)/config/infrastructure-config.json" | ConvertFrom-Json
                $env = $config.environments.prod
                
                Write-Host "Image Type: $(imageType)" -ForegroundColor Cyan
                Write-Host "Image Version: $(imageVersion)" -ForegroundColor Cyan
                Write-Host "Gallery: $($env.galleryName)" -ForegroundColor Gray
                Write-Host "Baseline: $($env.baselineImageName)" -ForegroundColor Gray
                Write-Host ""
                
                # Set working directory
                Set-Location "$(Build.SourcesDirectory)/images/packer/teams"
                
                # Initialize Packer
                Write-Host "Initializing Packer..." -ForegroundColor Cyan
                packer init $(imageFile)
                
                # Build the team image
                Write-Host "Building $(imageType) image..." -ForegroundColor Cyan
                packer build `
                  -var "subscription_id=$env:ARM_SUBSCRIPTION_ID" `
                  -var "resource_group_name=$($env.galleryResourceGroup)" `
                  -var "gallery_name=$($env.galleryName)" `
                  -var "baseline_image_version=1.0.0" `
                  -var "image_version=$(imageVersion)" `
                  -var "location=$($env.region)" `
                  $(imageFile)
                
                if ($LASTEXITCODE -ne 0) {
                  Write-Error "$(imageType) image build failed"
                  exit 1
                }
                
                Write-Host ""
                Write-Host ("[SUCCESS] {0} image built successfully" -f "$(imageType)") -ForegroundColor Green
            displayName: 'Build $(imageType) Image'
            env:
              ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)

  - stage: PublishManifest
    displayName: 'Publish Image Manifest'
    dependsOn: BuildTeamImages
    condition: succeeded()
    jobs:
      - job: CreateManifest
        displayName: 'Create Image Version Manifest'
        steps:
          - checkout: self
          
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'DevBox-Images-ServiceConnection'
              scriptType: 'pscore'
              scriptLocation: 'inlineScript'
              inlineScript: |
                Write-Host "Creating image version manifest..."
                
                # Read infrastructure config
                $config = Get-Content "config/infrastructure-config.json" | ConvertFrom-Json
                $env = $config.environments.prod
                
                # Get all image versions from gallery
                $images = az sig image-version list `
                  --resource-group $env.galleryResourceGroup `
                  --gallery-name $env.galleryName `
                  --query "[?publishingProfile.publishedDate > '$(Get-Date -Format 'yyyy-MM-dd')']" | ConvertFrom-Json
                
                $manifest = @{
                  buildNumber = "$(Build.BuildNumber)"
                  buildDate = (Get-Date -Format "o")
                  repository = "microsoft.devcenter-images"
                  environment = "prod"
                  images = @()
                }
                
                foreach ($img in $images) {
                  $manifest.images += @{
                    name = $img.name
                    version = $img.id.Split('/')[-1]
                    publishedDate = $img.publishingProfile.publishedDate
                  }
                }
                
                $manifest | ConvertTo-Json -Depth 10 | Out-File "$(Build.ArtifactStagingDirectory)/image-manifest.json"
                
                Write-Host "Manifest created with $($manifest.images.Count) images"
            displayName: 'Generate Manifest'
          
          - task: PublishBuildArtifacts@1
            inputs:
              pathToPublish: '$(Build.ArtifactStagingDirectory)'
              artifactName: 'image-manifest'
            displayName: 'Publish Manifest Artifact'

  - stage: TriggerSync
    displayName: 'Trigger Definition Sync'
    dependsOn: PublishManifest
    condition: succeeded()
    jobs:
      - job: TriggerSyncPipeline
        displayName: 'Trigger sync-definitions-and-pools Pipeline'
        steps:
          - task: InvokeRESTAPI@1
            displayName: 'Trigger Sync Pipeline'
            inputs:
              connectionType: 'connectedServiceName'
              serviceConnection: 'AzureDevOps-ServiceConnection'
              method: 'POST'
              urlSuffix: '/_apis/pipelines/$(SyncPipelineId)/runs?api-version=7.1'
              body: |
                {
                  "resources": {
                    "repositories": {
                      "self": {
                        "refName": "refs/heads/main"
                      }
                    }
                  }
                }
              waitForCompletion: 'false'
